### ISSUE TITLE
Revise the npm release process

### ISSUE THREAD

**Issue by morungos** [atariman486/node-ole-doc#5]
Currently @atariman486 is the only npm owner, so we can't push a new release to npm just yet. I'd suggest the following:
- Maybe (if you're okay with it) add me (I'm morungos on npm) as an additional owner, then I can push too, Should just require "npm owner add morungos ole-doc".
- I'd also suggest setting up a develop branch in git, mainly to make the release process a bit simpler through git flow

If you can do the first of these, I'll be happy to update the versions in files, tag and push a 0.1.1 release, which will make everyone happy.

**Comment by atariman486** [comment]
Added you as an owner!

**Comment by atariman486** [comment]
Leaving open for the second part

**Comment by morungos** [comment]
Didn't do this quite right first time. npm version and git flow kind of interfered, and I didn't get the change log right either. Ah well. Lessons learned for next time. And 0.1.1 is now pushed to npm.
